#[[docs]]
#  name = "About Hugo"
#  weight = 10
#  identifier = "about"
#  url = "/about/"
#
#[[docs]]
#  name = "Installation"
#  weight = 20
#  identifier = "installation"
#  url = "/installation/"
#
#[[docs]]
#  name = "Getting Started"
#  weight = 30
#  identifier = "getting-started"
#  url = "/getting-started/"
#
#[[docs]]
#  name = "Hugo Modules"
#  weight = 40
#  identifier = "modules"
#  post = "break"
#  url = "/hugo-modules/"
#
## Core menus
#
#[[docs]]
#  name = "Content Management"
#  weight = 50
#  identifier = "content-management"
#  post = "expanded"
#  url = "/content-management/"
#
#[[docs]]
#  name = "Templates"
#  weight = 60
#  identifier = "templates"
#  url = "/templates/"
#
#[[docs]]
#  name = "Functions"
#  weight = 70
#  identifier = "functions"
#  url = "/functions/"
#
#[[docs]]
#  name = "Variables"
#  weight = 80
#  identifier = "variables"
#  url = "/variables/"
#
#[[docs]]
#  name = "Hugo Pipes"
#  weight = 90
#  identifier = "pipes"
#  url = "/hugo-pipes/"
#
#[[docs]]
#  name = "CLI"
#  weight = 100
#  post = "break"
#  identifier = "commands"
#  url = "/commands/"
#
## Low level items
#
#[[docs]]
#  name = "Troubleshooting"
#  weight = 110
#  identifier = "troubleshooting"
#  url = "/troubleshooting/"
#
#[[docs]]
#  name = "Tools"
#  weight = 120
#  identifier = "tools"
#  url = "/tools/"
#
#[[docs]]
#  name = "Hosting & Deployment"
#  weight = 130
#  identifier = "hosting-and-deployment"
#  url = "/hosting-and-deployment/"

#[[docs]]
#  name = "Contribute"
#  weight = 140
#  post = "break"
#  identifier = "contribute"
#  url = "/contribute/"

######## QUICKLINKS

#[[quicklinks]]
#  name = "Fundamentals"
#  weight = 1
#  identifier = "fundamentals"
#  url = "/tags/fundamentals/"

######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
  name = "Technology"
  weight = 1
  identifier = "tech"
  url = "/technology/"

[[global]]
  name = "Blogs"
  weight = 5
  identifier = "blogs"
  url = "/blogs/"

[[global]]
    name = "Events"
    weight = 10
    identifier = "events"
    url = "/events/"


# Anything with a weight > 100 gets an external icon

[[global]]
  name = "GitHub"
  weight = 150
  identifier = "github"
  post = "external"
  url = "https://github.com/Committable"

[[global]]
  name = "Launch App"
  weight = 200
  icon = true
  identifier = "app"
  post = "external"
  url = "https://app-test.committable.io/"